version: "3"

services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: hexTrainer_mariadb
    restart: always
    networks:
        - database
    volumes:
      - ~/services/codimd_database/mariadb_config:/config
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=hexTrainer
      - MYSQL_USER=hexTrainer
      - MYSQL_PASSWORD=12345
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London



  frontend:
    image: nginx
    restart: always
    container_name: hexTrainer
    volumes:
      - ./app:/usr/share/nginx/html
    labels:
      - traefik.frontend.rule=Host:trainer.exmd.de
      - traefik.docker.network=traefik_net
      - traefik.enable=true
      - traefik.port=80
    networks:
      - traefik_net
      - database

networks:
  traefik_net:
    external: true
  database:

volumes:
  frontend:
  mariadb:

