version: "3"

services:
  frontend:
    image: nginx
    restart: always
    volumes:
      - ./app:/usr/share/nginx/html
    labels:
      - traefik.frontend.rule=Host:trainer.exmd.de
      - traefik.docker.network=traefik_net
      - traefik.enable=true
      - traefik.port=80
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true

